services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres-dev

  postgres-dev:
    image: postgres
    environment:
      POSTGRES_USER: "kicoma-dev"
      POSTGRES_PASSWORD: "kicoma-dev"