services:
  web:
    build: .
    # command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
      - ./storage:/django/storage
    ports:
      - "8000:8000"
    # depends_on:
    #   - redis

  # redis:
  #   image: redis:7.4.2
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - /var/redis/data:/data
