# Generated by Django 3.0.5 on 2020-04-24 15:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Kód alergénu', max_length=10, unique=True, verbose_name='Kód')),
                ('description', models.CharField(help_text='Název alergénu', max_length=100, unique=True, verbose_name='Název')),
            ],
            options={
                'verbose_name_plural': 'Alergény',
            },
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Druh jídla v rámci dne', max_length=30, unique=True, verbose_name='Druh jídla')),
                ('category', models.CharField(help_text='Kategorie druhu jídla', max_length=30, verbose_name='Kategorie')),
            ],
            options={
                'verbose_name_plural': 'Druhy jídla',
            },
        ),
        migrations.CreateModel(
            name='StockUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Objemová nebo váhová jednotka zboží', max_length=2, unique=True, verbose_name='Jednotka')),
            ],
            options={
                'verbose_name_plural': 'Jednotky',
            },
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Skupina pro kterou se připravuje jídlo', max_length=100, unique=True, verbose_name='Skupina strávníka')),
            ],
            options={
                'verbose_name_plural': 'Skupiny strávníků',
            },
        ),
        migrations.CreateModel(
            name='VAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveSmallIntegerField(help_text='DPH procenta', unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Výše')),
                ('name', models.CharField(help_text='DPH sazba', max_length=100, unique=True, verbose_name='Sazba')),
            ],
            options={
                'verbose_name_plural': 'DPH',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Skladová položka')),
                ('criticalAmount', models.PositiveSmallIntegerField(help_text='Minimální množství na skladu', unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Kritické množství')),
                ('averagePrice', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Průměrná cena')),
                ('normPrice', models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True, verbose_name='Cena normy')),
                ('comment', models.CharField(max_length=200, verbose_name='Poznámka')),
                ('coefficient', models.DecimalField(decimal_places=4, default=1, help_text='Koeficient  propočtu do receptu', max_digits=5, verbose_name='Koeficient')),
                ('allergen', models.ManyToManyField(blank=True, to='kitchen.Allergen', verbose_name='Alergény')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.StockUnit', verbose_name='Jednotka')),
            ],
            options={
                'verbose_name_plural': 'Skladové položky',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, help_text='Množství suroviny', max_digits=6, unique=True, verbose_name='Množství')),
                ('stockItem', models.ForeignKey(help_text='Skladová položka', on_delete=django.db.models.deletion.CASCADE, to='kitchen.StockItem', verbose_name='Skladová položka')),
            ],
            options={
                'verbose_name_plural': 'Suroviny v receptu',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Jméno')),
                ('norm_amount', models.PositiveSmallIntegerField(help_text='Počet porcí', verbose_name='Normovaný počet')),
                ('comment', models.CharField(max_length=200, verbose_name='Poznámka')),
                ('recipeIngredient', models.ForeignKey(help_text='Suroviny v receptu', on_delete=django.db.models.deletion.CASCADE, to='kitchen.RecipeIngredient', verbose_name='Seznam surovin')),
            ],
            options={
                'verbose_name_plural': 'Recepty',
            },
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('amount', models.PositiveSmallIntegerField(help_text='Počet porcí', unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Počet')),
                ('mealType', models.ForeignKey(help_text='Druh jídla v rámci dne', on_delete=django.db.models.deletion.CASCADE, to='kitchen.MealType', verbose_name='Druh jídla')),
                ('recipe', models.ForeignKey(help_text='Vybraný recept', on_delete=django.db.models.deletion.CASCADE, to='kitchen.Recipe', verbose_name='Recept')),
                ('targetGroup', models.ForeignKey(help_text='Skupina pro kterou se připravuje jídlo', on_delete=django.db.models.deletion.CASCADE, to='kitchen.TargetGroup', verbose_name='Skupina strávníka')),
            ],
            options={
                'verbose_name_plural': 'Denní jídlo',
            },
        ),
    ]
