# Generated by Django 3.0.5 on 2020-04-13 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Skratka')),
                ('description', models.CharField(max_length=100, verbose_name='Název')),
            ],
            options={
                'verbose_name_plural': 'Alergeny',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název')),
                ('category', models.CharField(max_length=100, verbose_name='Kategorie')),
            ],
            options={
                'verbose_name_plural': 'Druhy jídla',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Množství')),
            ],
            options={
                'verbose_name_plural': 'Recept',
            },
        ),
        migrations.CreateModel(
            name='StockUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, verbose_name='Jednotka')),
            ],
            options={
                'verbose_name_plural': 'Jednotky',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Skupina strávníka')),
            ],
            options={
                'verbose_name_plural': 'Skupiny strávníků',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unikátní kód skladové položky', max_length=6, unique=True, verbose_name='Kód')),
                ('name', models.CharField(max_length=100, verbose_name='Název ingredence')),
                ('coefficient', models.DecimalField(decimal_places=4, default=1, max_digits=5, verbose_name='Koeficient')),
                ('in_stock', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Skladem')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena')),
                ('cena_normy', models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('allergen', models.ManyToManyField(blank=True, to='kitchen.Allergen', verbose_name='Alergény')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.StockUnit', verbose_name='Jednotka')),
            ],
            options={
                'verbose_name_plural': 'Skladové položky',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RecipeBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Kód')),
                ('name', models.CharField(max_length=100, verbose_name='Jméno')),
                ('norm_amount', models.PositiveSmallIntegerField(verbose_name='Normovaný počet')),
                ('ingredients', models.ManyToManyField(through='kitchen.Recipe', to='kitchen.StockItem')),
            ],
            options={
                'verbose_name_plural': 'Recepty',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.StockItem'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipeBook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.RecipeBook'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.StockUnit', verbose_name='Jednotka'),
        ),
    ]
