# Generated by Django 3.0.7 on 2020-06-19 16:53

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Kód alergénu', max_length=10, unique=True, verbose_name='Kód')),
                ('description', models.CharField(help_text='Název alergénu', max_length=150, unique=True, verbose_name='Název')),
            ],
            options={
                'verbose_name': 'číselník - Alergén',
                'verbose_name_plural': 'číselník - Alergény',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Kód zboží', max_length=10, unique=True, verbose_name='Kód')),
                ('name', models.CharField(help_text='Název zboží na skladu', max_length=30, unique=True, verbose_name='Název zboží')),
                ('onStock', models.DecimalField(decimal_places=2, default=0, help_text='Celkové množství na skladu', max_digits=8, verbose_name='Na skladu')),
                ('averagePrice', models.DecimalField(blank=True, decimal_places=2, help_text='Vypočtena průměrná cena na jednotku', max_digits=6, null=True, verbose_name='Průměrná jednotková cena')),
                ('unit', models.CharField(choices=[('kg', 'kilogram'), ('g', 'gram'), ('l', 'litr'), ('ml', 'mililitr'), ('ks', 'kus')], max_length=2, verbose_name='Jednotka')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('allergen', models.ManyToManyField(blank=True, to='kitchen.Allergen', verbose_name='Alergény')),
            ],
            options={
                'verbose_name': 'Zboží',
                'verbose_name_plural': 'Zboží',
            },
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('amount', models.PositiveSmallIntegerField(help_text='Počet porcí', unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Počet')),
            ],
            options={
                'verbose_name': 'Denní jídlo',
                'verbose_name_plural': 'Denní jídla',
            },
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Druh jídla v rámci dne', max_length=30, unique=True, verbose_name='Druh jídla')),
            ],
            options={
                'verbose_name': 'číselník - Druh jídla',
                'verbose_name_plural': 'číselník - Druhy jídla',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Název receptu', max_length=100, unique=True, verbose_name='Jméno')),
                ('norm_amount', models.PositiveSmallIntegerField(help_text='Počet porcí', verbose_name='Normovaný počet')),
                ('procedure', models.TextField(blank=True, max_length=200, null=True, verbose_name='Postup')),
            ],
            options={
                'verbose_name': 'Recept',
                'verbose_name_plural': 'Recepty',
            },
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Skupina pro kterou se připravuje jídlo', max_length=100, unique=True, verbose_name='Skupina strávníka')),
            ],
            options={
                'verbose_name': 'číselník - Skupina strávníků',
                'verbose_name_plural': 'číselník - Skupiny strávníků',
            },
        ),
        migrations.CreateModel(
            name='VAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveSmallIntegerField(help_text='DPH procenta', unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Výše')),
                ('name', models.CharField(help_text='DPH sazba', max_length=100, unique=True, verbose_name='Sazba')),
            ],
            options={
                'verbose_name': 'číselník - DPH',
                'verbose_name_plural': 'číselník - DPH',
            },
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(default=datetime.date.today, verbose_name='Datum vytvoření')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('userCreated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to=settings.AUTH_USER_MODEL, verbose_name='Přijal')),
            ],
            options={
                'verbose_name': 'Příjemka',
                'verbose_name_plural': 'Příjemky',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='StockIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(verbose_name='Datum vytvoření')),
                ('approved', models.BooleanField(blank=True, default=False, null=True, verbose_name='Odepsáno ze skladu')),
                ('approvedDate', models.DateField(blank=True, null=True, verbose_name='Datum odpisu ze skladu')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('dailyMenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.DailyMenu', verbose_name='Vydáno v menu')),
                ('userApproved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved', to=settings.AUTH_USER_MODEL, verbose_name='Odepsal ze skladu')),
                ('userCreated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
            ],
            options={
                'verbose_name': 'Výdejka',
                'verbose_name_plural': 'Výdejky',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Množství')),
                ('unit', models.CharField(choices=[('kg', 'kilogram'), ('g', 'gram'), ('l', 'litr'), ('ml', 'mililitr'), ('ks', 'kus')], max_length=2, verbose_name='Jednotka')),
                ('priceWithoutVat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena bez DPH')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Article', verbose_name='Zboží')),
                ('stockIssue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.StockIssue', verbose_name='Výdejka')),
                ('stockReceipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.StockReceipt', verbose_name='Příjemka')),
                ('vat', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.VAT', verbose_name='DPH')),
            ],
            options={
                'verbose_name': 'Položka',
                'verbose_name_plural': 'Položky',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Množství suroviny', max_digits=8, unique=True, verbose_name='Množství')),
                ('unit', models.CharField(choices=[('kg', 'kilogram'), ('g', 'gram'), ('l', 'litr'), ('ml', 'mililitr'), ('ks', 'kus')], max_length=2, verbose_name='Jednotka')),
                ('article', models.ForeignKey(help_text='Použitá surovina', on_delete=django.db.models.deletion.CASCADE, to='kitchen.Article', verbose_name='Surovina')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Recipe', verbose_name='Recept')),
            ],
            options={
                'verbose_name': 'Surovina v receptu',
                'verbose_name_plural': 'Suroviny v receptu',
            },
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='mealType',
            field=models.ForeignKey(help_text='Druh jídla v rámci dne', on_delete=django.db.models.deletion.CASCADE, to='kitchen.MealType', verbose_name='Druh jídla'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='recipe',
            field=models.ForeignKey(help_text='Vybraný recept', on_delete=django.db.models.deletion.CASCADE, to='kitchen.Recipe', verbose_name='Recept'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='targetGroup',
            field=models.ForeignKey(help_text='Skupina pro kterou se připravuje jídlo', on_delete=django.db.models.deletion.CASCADE, to='kitchen.TargetGroup', verbose_name='Skupina strávníka'),
        ),
    ]
