# Generated by Django 3.0.8 on 2020-07-07 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenurecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Počet porcí', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Počet'),
        ),
    ]
