# Generated by Django 3.1 on 2020-08-16 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceipt',
            name='date_created',
            field=models.DateField(default=datetime.date.today, verbose_name='Datum založení'),
        ),
    ]
