# Generated by Django 3.0.5 on 2020-04-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='description',
            field=models.CharField(help_text='Název alergénu', max_length=150, unique=True, verbose_name='Název'),
        ),
    ]
