# Generated by Django 3.1 on 2020-08-22 16:33

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalArticle',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Datum vytvoření')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='Datum aktualizace')),
                ('article', models.CharField(db_index=True, help_text='Název zboží na skladu', max_length=30, verbose_name='Zboží')),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('ml', 'ml'), ('ks', 'ks')], max_length=2, verbose_name='Jednotka')),
                ('on_stock', models.DecimalField(decimal_places=2, default=0, help_text='Celkové množství zboží na skladu', max_digits=8, verbose_name='Na skladu')),
                ('min_on_stock', models.DecimalField(decimal_places=2, default=0, help_text='Minimální množství zboží na skladu', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Minimálně na skladu')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Celková cena zboží na skladu', max_digits=8, null=True, verbose_name='Celková cena s DPH')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poznámka')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Zboží',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
