# Generated by Django 3.1 on 2020-08-24 08:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_auto_20200824_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='min_on_stock',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Minimální množství zboží na skladu', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Minimálně na skladu'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='min_on_stock',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Minimální množství zboží na skladu', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Minimálně na skladu'),
        ),
    ]
