# Generated by Django 3.1 on 2020-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_auto_20200827_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockreceiptarticle',
            options={'ordering': ['id'], 'verbose_name': 'Zboží na výdejce', 'verbose_name_plural': 'Zboží na příjemce'},
        ),
        migrations.AlterField(
            model_name='stockissuearticle',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Množství'),
        ),
        migrations.AlterField(
            model_name='stockissuearticle',
            name='average_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Průměrná jednotková cena s DPH'),
        ),
    ]
