# Generated by Django 3.1.1 on 2020-09-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_auto_20200828_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockreceiptarticle',
            options={'ordering': ['-id'], 'verbose_name': 'Zboží na příjemce', 'verbose_name_plural': 'Zboží na příjemce'},
        ),
    ]
