# Generated by Django 3.2.10 on 2022-02-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_auto_20211118_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergen',
            options={'verbose_name': 'číselník - Alergen', 'verbose_name_plural': 'číselník - Alergeny'},
        ),
        migrations.AlterField(
            model_name='allergen',
            name='code',
            field=models.CharField(help_text='Kód alergenu', max_length=10, unique=True, verbose_name='Kód'),
        ),
        migrations.AlterField(
            model_name='allergen',
            name='description',
            field=models.CharField(help_text='Název alergenu', max_length=150, unique=True, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='article',
            name='allergen',
            field=models.ManyToManyField(blank=True, to='kitchen.Allergen', verbose_name='Alergeny'),
        ),
    ]
