# Generated by Django 3.2.10 on 2022-02-27 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitchen', '0012_dailymenu_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['menu'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterField(
            model_name='stockissue',
            name='user_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_is_approved', to=settings.AUTH_USER_MODEL, verbose_name='Vyskladnil'),
        ),
        migrations.AlterField(
            model_name='stockissue',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_is_created', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='user_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_approved', to=settings.AUTH_USER_MODEL, verbose_name='Naskladnil'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil'),
        ),
    ]
