# Generated by Django 5.0.6 on 2024-06-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0013_auto_20220227_1753"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalarticle",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Zboží",
                "verbose_name_plural": "historical Zboží",
            },
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
