# Generated by Django 5.2 on 2025-04-27 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0014_alter_historicalarticle_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockreceiptarticle",
            name="vat",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="kitchen.vat",
                verbose_name="DPH",
            ),
        ),
    ]
