# Generated by Django 5.2 on 2025-06-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0015_alter_stockreceiptarticle_vat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockissuearticle",
            options={
                "ordering": ["article__article"],
                "verbose_name": "Zboží na výdejce",
                "verbose_name_plural": "Zboží na výdejce",
            },
        ),
    ]
