# Generated by Django 5.2 on 2025-09-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0016_alter_stockissuearticle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='dailymenurecipe',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='procedure',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Postup receptu'),
        ),
        migrations.AlterField(
            model_name='recipearticle',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='stockissue',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='stockissuearticle',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='stockreceiptarticle',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Poznámka'),
        ),
    ]
