# Generated by Django 5.2.6 on 2025-09-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0017_alter_article_comment_alter_dailymenu_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='date',
            field=models.DateField(help_text='Datum denního menu', verbose_name='Datum'),
        ),
    ]
