# Generated by Django 5.2.6 on 2025-09-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0019_alter_article_on_stock_alter_article_total_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='Kč', help_text='Mena', max_length=5)),
                ('demo_usage', models.PositiveIntegerField(default='0', help_text='Počet demo přístupů')),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(help_text='Název menu', max_length=100, unique=True, verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.CharField(help_text='Název receptu', max_length=100, unique=True, verbose_name='Recept'),
        ),
    ]
