# Generated by Django 5.2.6 on 2025-09-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0020_appsettings_alter_menu_menu_alter_recipe_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsettings',
            options={'verbose_name': 'Nastavení', 'verbose_name_plural': 'Nastavení'},
        ),
    ]
