# Generated by Django 5.2.6 on 2025-09-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0021_alter_appsettings_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='demo_usage',
        ),
    ]
