# Generated by Django 5.2.6 on 2025-09-27 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0022_remove_appsettings_demo_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenurecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Počet porcí', validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Porcí'),
        ),
        migrations.AlterField(
            model_name='menurecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Počet porcí', validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Porcí'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='norm_amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Porcí'),
        ),
        migrations.AlterField(
            model_name='vat',
            name='percentage',
            field=models.PositiveSmallIntegerField(help_text='DPH procenta', unique=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Výše'),
        ),
    ]
