# Generated by Django 5.2.6 on 2025-09-28 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0023_alter_dailymenurecipe_amount_alter_menurecipe_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menurecipe',
            options={'ordering': ['recipe'], 'verbose_name': 'Recepty menu', 'verbose_name_plural': 'Recepty menu'},
        ),
        migrations.AlterModelOptions(
            name='recipearticle',
            options={'ordering': ['article'], 'verbose_name': 'Surovina v receptu', 'verbose_name_plural': 'Suroviny v receptu'},
        ),
        migrations.AlterModelOptions(
            name='stockissuearticle',
            options={'ordering': ['article'], 'verbose_name': 'Zboží na výdejce', 'verbose_name_plural': 'Zboží na výdejce'},
        ),
        migrations.AlterModelOptions(
            name='stockreceiptarticle',
            options={'ordering': ['article'], 'verbose_name': 'Zboží na příjemce', 'verbose_name_plural': 'Zboží na příjemce'},
        ),
    ]
