# Generated by Django 6.1 on 2026-08-26 18:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0024_alter_menurecipe_options_alter_recipearticle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Sacharidy (g/100 g)'),
        ),
        migrations.AddField(
            model_name='article',
            name='energy',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Energie (kJ/100 g)'),
        ),
        migrations.AddField(
            model_name='article',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tuky (g/100 g)'),
        ),
        migrations.AddField(
            model_name='article',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Vláknina (g/100 g)'),
        ),
        migrations.AddField(
            model_name='article',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Bílkoviny (g/100 g)'),
        ),
        migrations.AddField(
            model_name='article',
            name='sugars',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cukry (g/100 g)'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Sacharidy (g/100 g)'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='energy',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Energie (kJ/100 g)'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tuky (g/100 g)'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Vláknina (g/100 g)'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Bílkoviny (g/100 g)'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='sugars',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cukry (g/100 g)'),
        ),
    ]
