# Generated by Django 6.1 on 2026-08-26 18:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0025_article_carbohydrates_article_energy_article_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Sacharidy'),
        ),
        migrations.AlterField(
            model_name='article',
            name='energy',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='kJ / 100 g', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3800)], verbose_name='Energie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tuky'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Vláknina'),
        ),
        migrations.AlterField(
            model_name='article',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Bílkoviny'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sugars',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cukry'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Sacharidy'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='energy',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='kJ / 100 g', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3800)], verbose_name='Energie'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tuky'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Vláknina'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Bílkoviny'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='sugars',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cukry'),
        ),
    ]
