# Generated by Django 6.1.1 on 2026-09-20 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0028_article_monounsaturated_fat_article_polyols_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='energy',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='kJ / 100 g', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Energie'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='energy',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='kJ / 100 g', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Energie'),
        ),
    ]
