# Generated by Django 6.1.1 on 2026-09-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0029_alter_article_energy_alter_historicalarticle_energy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='monounsaturated_fat',
        ),
        migrations.RemoveField(
            model_name='article',
            name='polyols',
        ),
        migrations.RemoveField(
            model_name='article',
            name='polyunsaturated_fat',
        ),
        migrations.RemoveField(
            model_name='article',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='article',
            name='starch',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='monounsaturated_fat',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='polyols',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='polyunsaturated_fat',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='starch',
        ),
    ]
