# Generated by Django 6.1.1 on 2026-10-04 18:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0030_remove_article_monounsaturated_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='piece_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pro zboží v ks: hmotnost nebo objem jednoho kusu', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Hmotnost kusu'),
        ),
        migrations.AddField(
            model_name='article',
            name='piece_weight_unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('ml', 'ml')], max_length=2, null=True, verbose_name='Jednotka hmotnosti kusu'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='piece_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pro zboží v ks: hmotnost nebo objem jednoho kusu', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Hmotnost kusu'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='piece_weight_unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('ml', 'ml')], max_length=2, null=True, verbose_name='Jednotka hmotnosti kusu'),
        ),
        migrations.AddField(
            model_name='stockissue',
            name='menu_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum denního menu'),
        ),
        migrations.AlterField(
            model_name='article',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g (ml)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Sacharidy'),
        ),
        migrations.AlterField(
            model_name='article',
            name='energy',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='kJ / 100 g (ml)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Energie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g (ml)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tuky'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g (ml)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Vláknina'),
        ),
        migrations.AlterField(
            model_name='article',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g (ml)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Bílkoviny'),
        ),
        migrations.AlterField(
            model_name='article',
            name='saturated_fat',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g (ml)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='z toho nasycené mastné kyseliny'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sugars',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g (ml)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='z toho cukry'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g (ml)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Sacharidy'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='energy',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='kJ / 100 g (ml)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Energie'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g (ml)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tuky'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g (ml)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Vláknina'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g (ml)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Bílkoviny'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='saturated_fat',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g (ml)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='z toho nasycené mastné kyseliny'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='sugars',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='g / 100 g (ml)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='z toho cukry'),
        ),
        migrations.AlterField(
            model_name='stockissuearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kitchen.article', verbose_name='Zboží'),
        ),
        migrations.AlterField(
            model_name='stockissuearticle',
            name='average_unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Průměrná jednotková cena s DPH'),
        ),
        migrations.AlterField(
            model_name='stockreceiptarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockreceiptarticle_set', to='kitchen.article', verbose_name='Zboží'),
        ),
        migrations.AlterField(
            model_name='stockreceiptarticle',
            name='price_without_vat',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Jednotková cena bez DPH'),
        ),
    ]
