# Generated by Django 6.1.1 on 2026-10-04 19:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0031_high_priority_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='norm_amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Porcí'),
        ),
        migrations.AlterField(
            model_name='stockissue',
            name='user_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_is_approved', to=settings.AUTH_USER_MODEL, verbose_name='Vyskladnil'),
        ),
        migrations.AlterField(
            model_name='stockissue',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_is_created', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='user_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_approved', to=settings.AUTH_USER_MODEL, verbose_name='Naskladnil'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_created', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil'),
        ),
    ]
