# Generated by Django 6.1.1 on 2026-10-04 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0032_medium_priority_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreceipt',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum založení'),
        ),
    ]
