# Generated by Django 6.1.1 on 2026-10-04 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0033_low_priority_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreceiptarticle',
            name='vat',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='kitchen.vat', verbose_name='DPH'),
        ),
    ]
