# Generated by Django 6.1.1 on 2026-10-04 20:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0034_protect_receipt_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipearticle',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Množství suroviny', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Množství'),
        ),
        migrations.AlterField(
            model_name='stockreceiptarticle',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Množství'),
        ),
    ]
