# Generated by Django 6.1.1 on 2026-10-04 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0035_minimum_line_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('article', 'Zboží'), ('recipe_line', 'Surovina v receptu'), ('undo', 'Vrácení změny')], max_length=20, verbose_name='Druh')),
                ('article_name', models.CharField(max_length=30, verbose_name='Název zboží')),
                ('old_unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('ml', 'ml'), ('ks', 'ks')], max_length=2, verbose_name='Původní jednotka')),
                ('new_unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('ml', 'ml'), ('ks', 'ks')], max_length=2, verbose_name='Nová jednotka')),
                ('factor', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Převodní koeficient')),
                ('source_note', models.CharField(max_length=200, verbose_name='Zdroj koeficientu')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Podrobnosti')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_changes', to='kitchen.article', verbose_name='Zboží')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_changes', to='kitchen.recipe', verbose_name='Recept')),
                ('undo_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undone_by', to='kitchen.unitchangelog', verbose_name='Vrácená změna')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_changes', to=settings.AUTH_USER_MODEL, verbose_name='Změnil')),
            ],
            options={
                'verbose_name': 'Změna jednotky',
                'verbose_name_plural': 'Změny jednotek',
                'ordering': ['-created', '-id'],
            },
        ),
    ]
