@startuml "KiCoMa"

DailyMenu_DenniMenu -- Recipe_Recept : > je_slozeno_s

DailyMenu_DenniMenu -- TargetGroup_SkupinaStravniku : je_vydano_pro >
MealType_TypJidla - DailyMenu_DenniMenu : < patri_do
TargetGroup_SkupinaStravniku -[hidden] Recipe_Recept

Recipe_Recept - Ingredients_Suroviny : obsahuje >
Article_Zbozi -- Ingredients_Suroviny : > se_sklada_ze
Ingredients_Suroviny -- Unit_Jednotka : je_pocitano_v >

Allergen_Alergeny -- Article_Zbozi : obsahuje <
Unit_Jednotka - Stock_Sklad : je_pocitano_v <

Article_Zbozi -- Stock_Sklad : ma_zasoby >

StockReceipt_Prijemka -- Item_Polozka : obsahuje >
Item_Polozka - Article_Zbozi : obsahuje >
Item_Polozka -- Unit_Jednotka : je_pocitano_v >
VAT_DPH - Item_Polozka : obsahuje <

StockIssue_Vydejka - Item_Polozka : obsahuje >
StockIssue_Vydejka -- DailyMenu_DenniMenu : automaticky_vytvari <

User_Uzivatel - StockReceipt_Prijemka : zaklada >
StockIssue_Vydejka - User_Uzivatel : potvrzuje i zakládá <

class VAT_DPH {
    *id <<generated>>
    *code / Skratka
    --
    * percentage / Procento
}

class Allergen_Alergeny {
    *id <<generated>>
    *code / Skratka
    --
    *description / Název
}

class Unit_Jednotka {
    *id <<generated>>
    --
    *name / Jednotka
}

class TargetGroup_SkupinaStravniku {
    *id <<generated>>
    --
    *name / Skupina strávníků
}

class MealType_TypJidla {
    *id <<generated>>
    --
    *name / Název
    category / Kategorie
}

class DailyMenu_DenniMenu {
    *id <<generated>>
    --
    *date / datum
    *amount / Počet
}

class Recipe_Recept {
    *id <<generated>>
    *code / Katalogové číslo
    --
    name / Název receptu
    normAmount / Normované množství
    comment / Poznámka
    recipeText / Popis
    picture / Obrázek
    dateCreated / Datum založení
}

class Ingredients_Suroviny {
    *id <<generated>>
    --
    amount / Množství
}

class Article_Zbozi {
    *id <<generated>>
    *code / Katalogové číslo
    --
    *name / Název ingredence
    criticalAmount / Kritické množství
    averagePrice / Průměrná cena
    norm_price / cena_normy
    comment / Poznámka
    picture / Obrázek
}

class Item_Polozka {
    *id <<generated>>
    --
    amount / Množství
    price_without_vat / Cena bez DPH
    price_with_vat / Cena s DPH
    comment / Poznámka
}

class StockReceipt_Prijemka {
    *id <<generated>>
    --
    * created_date / Vytvořeno dne
    comment / Poznámka
}

class StockIssue_Vydejka {
    *id <<generated>>
    --
    * created_date / Vytvořeno dne
    * approced_date / Schváleno dne
    comment / Poznámka
}

class Stock_Sklad {
    *id <<generated>>
    --
    amount / Počet
}

class User_Uzivatel {
    *id <<generated>>
    --
    username / Uževatelské jméno
    first_name / Jméno
    last_name / Příjmení
    email / Email
    password / Heslo
    user_permissions / Práva
    is_active / Je aktivní/neaktivní
    last_login / Datum posledního přihlášení
    date_joined / Datum založení
}

@enduml
