@startuml "KiCoMa"

DailyMenu_DenniMenu --- Recipe_Recept : > je_slozeno_s

MealGroup_SkupinaStravniku -- DailyMenu_DenniMenu : je_vydano_pro >
DailyMenu_DenniMenu -[hidden] Item_Polozka
DailyMenu_DenniMenu -- MealType_TypJidla: patri_do >

Recipe_Recept - Ingredients_Suroviny : obsahuje >
Article_Zbozi --- Ingredients_Suroviny : obsahuje <

Allergen_Alergeny -- Article_Zbozi : obsahuje <

StockReceipt_Prijemka -- Item_Polozka : obsahuje >
Item_Polozka - Article_Zbozi : obsahuje >
Item_Polozka -- VAT_DPH : obsahuje >

StockIssue_Vydejka - Item_Polozka : obsahuje >
StockIssue_Vydejka -- DailyMenu_DenniMenu : automaticky_vytvari <

User_Uzivatel -- StockReceipt_Prijemka : zaklada >
User_Uzivatel -- StockIssue_Vydejka : potvrzuje i zakládá >

class VAT_DPH {
    * percentage / DPH procenta
    * rate / DPH sazba
}

class Allergen_Alergeny {
    *code / Kód alergénu
    *description / Název alergénu
}

class MealGroup_SkupinaStravniku {
    *mealGroup / Skupina strávníka
}

class MealType_TypJidla {
    *mealType / Druh jídla
}

class DailyMenu_DenniMenu {
    *date / datum
    *amount / Počet
}

class Recipe_Recept {
    *recipe / Název receptu
    *normAmount / Počet porcí
    procedure / Postup
}

class Ingredients_Suroviny {
    *amount / Množství
    *unit / Jednotka
}

class Article_Zbozi {
    *article / Název zboží
    onStock / Na skladu
    averagePrice / Průměrná jednotková cena
    *unit / Jednotka
    comment / Poznámka
}

class Item_Polozka {
    *amount / Množství
    *unit / Jednotka
    *price_without_vat / Cena bez DPH
    price_with_vat / Cena s DPH
    comment / Poznámka
}

class StockReceipt_Prijemka {
    * dateCreated / Datum vytvoření
    * userCreated / Přijal
    comment / Poznámka
}

class StockIssue_Vydejka {
    * dateCreated / Datum vytvoření
    * userCreated / Vytvořil
    approved / Odepsáno ze skladu
    userApproved / Odepsal ze skladu
    dateApproved / Datum odpisu ze skladu
    comment / Poznámka
}

class User_Uzivatel {
    username / Uživatelské jméno
    first_name / Jméno
    last_name / Příjmení
    email / Email
    password / Heslo
    user_permissions / Práva
    is_active / Je aktivní/neaktivní
    last_login / Datum posledního přihlášení
    date_joined / Datum založení
}

@enduml
